### PR TITLE
Fix typo at input reading

### PR DESCRIPTION
**Pull request by MOZGIII**
The whole action should probably fail if no permission requirement is detected.

### CODE REVIEW

**Comment by MOZGIII** [comment]
@lannonbr given the nature of this action, it is most definitely a security concern. I didn't realize this initially. Sorry for reporting this publicly, please process asap.

**Review by lannonbr — APPROVED** [review]
LGTM. I'll merge and tag a new release

**Comment by lannonbr** [comment]
This should be fixed now. You can use the `2.0.1` version.

**Comment by MOZGIII** [comment]
Thanks!

**Pull request merged**
